
receivers:
 otlp:
   protocols:
     grpc:
       endpoint: 0.0.0.0:4317
     http:
       endpoint: 0.0.0.0:4318
 prometheus:
     config:
       scrape_configs:
         - job_name: 'frontend-app'
           static_configs:
             - targets: ['frontend:5000']


exporters:
 otlp/jaeger:
   endpoint: http://jaeger:4317
   tls:
     insecure: true
 debug:
   verbosity: detailed

 otlphttp/logs:
   endpoint: "http://loki:3100/otlp"
   tls:
     insecure: true

 prometheus:
     endpoint: "0.0.0.0:8889"


service:
 pipelines:
   traces:
     receivers: [otlp]
     exporters: [debug, otlp/jaeger]
   metrics:
     receivers: [otlp]
     exporters: [debug, prometheus]
   logs:
     receivers: [otlp]
     exporters: [debug, otlphttp/logs]





============================================================================
# receivers:
#  otlp:
#    protocols:
#      grpc:
#        endpoint: 0.0.0.0:4317
#      http:
#        endpoint: 0.0.0.0:4318
# exporters:
#  otlp/jaeger:
#    endpoint: http://jaeger:4317
#    tls:
#      insecure: true
#  debug:
#    verbosity: detailed

#  otlphttp/logs:
#    endpoint: "http://loki:3100/otlp"
#    tls:
#      insecure: true

# service:
#  pipelines:
#    traces:
#      receivers: [otlp]
#      exporters: [debug, otlp/jaeger]
#    metrics:
#      receivers: [otlp]
#      exporters: [debug]
#    logs:
#      receivers: [otlp]
#      exporters: [debug, otlphttp/logs]



# # To limit exposure to denial of service attacks, change the host in endpoints below from 0.0.0.0 to a specific network interface.
# # See https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks

# extensions:
#   health_check:
#   pprof:
#     endpoint: 0.0.0.0:1777
#   zpages:
#     endpoint: 0.0.0.0:55679

# receivers:
#   otlp:
#     protocols:
#       grpc:
#         endpoint: 0.0.0.0:4317
#       http:
#         endpoint: 0.0.0.0:4318
#   prometheus:
#     config:
#       scrape_configs:
#         - job_name: "python-app"
#           scrape_interval: 15s
#           static_configs:
#             - targets: ["localhost:5000"]


# exporters:
#   debug:
#     verbosity: detailed
#   otlp/jaeger:
#     endpoint: 0.0.0.0:14251
#     tls:
#       insecure: true
#   prometheusremotewrite:
#     endpoint: "http://prometheus:9090/api/v1/write"

# service:

#   pipelines:

#     traces:
#       receivers: [otlp]
#       exporters: [otlp/jaeger]

#     metrics:
#       receivers: [otlp, prometheus]
#       exporters: [debug, prometheusremotewrite]

#     logs:
#       receivers: [otlp]
#       exporters: [debug]

#   extensions: [health_check, pprof, zpages]
